export const WebinarsRecords = [
    {
      id: 1,
      title: 'Telemedicine: Transforming Patient Care',
      date: '2024-08-15',
      description: 'Explore how telemedicine is revolutionizing healthcare delivery and patient engagement.',
      link: '#',
    },
    {
      id: 2,
      title: 'AI in Healthcare: Opportunities and Challenges',
      date: '2024-08-20',
      description: 'Understand the role of artificial intelligence in modern healthcare and its potential impact.',
      link: '#',
    },
    {
      id: 3,
      title: 'Hospital Management Systems: Best Practices',
      date: '2024-09-05',
      description: 'Learn about effective hospital management systems and strategies for implementation.',
      link: '#',
    },
    {
      id: 4,
      title: 'Cybersecurity in Healthcare: Protecting Patient Data',
      date: '2024-09-10',
      description: 'Discover the importance of cybersecurity in healthcare and ways to safeguard sensitive information.',
      link: '#',
    },
    {
      id: 5,
      title: 'Advancements in Medical Imaging Technology',
      date: '2024-09-12',
      description: 'Explore the latest advancements in medical imaging and their applications in diagnostics.',
      link: '#',
    },
    {
      id: 6,
      title: 'Ethical Considerations in Healthcare AI',
      date: '2024-09-15',
      description: 'Discuss the ethical implications of using AI in healthcare, including patient privacy and decision-making.',
      link: '#',
    },
    {
      id: 7,
      title: 'Implementing Electronic Health Records (EHR)',
      date: '2024-09-18',
      description: 'Learn how to effectively implement and manage electronic health records in your hospital.',
      link: '#',
    },
    {
      id: 8,
      title: 'Optimizing Hospital Workflow with Technology',
      date: '2024-09-20',
      description: 'Discover strategies for using technology to streamline hospital workflows and improve efficiency.',
      link: '#',
    },
    {
      id: 9,
      title: 'Wearable Devices in Healthcare: Trends and Future',
      date: '2024-09-22',
      description: 'Explore the role of wearable devices in monitoring patient health and the future of this technology.',
      link: '#',
    },
    {
      id: 10,
      title: 'Patient-Centered Care: Strategies and Practices',
      date: '2024-09-25',
      description: 'Learn how to implement patient-centered care models in your hospital for improved outcomes.',
      link: '#',
    },
    {
      id: 11,
      title: 'Data Analytics in Healthcare: Enhancing Decision Making',
      date: '2024-09-28',
      description: 'Discover how data analytics can improve decision-making processes in healthcare.',
      link: '#',
    },
    {
      id: 12,
      title: 'Innovations in Surgical Technology',
      date: '2024-10-01',
      description: 'Explore the latest innovations in surgical technology and their impact on patient care.',
      link: '#',
    },
    {
      id: 13,
      title: 'Healthcare Informatics: Integrating Technology and Medicine',
      date: '2024-10-05',
      description: 'Learn how healthcare informatics integrates technology and medicine to improve patient care.',
      link: '#',
    },
    {
      id: 14,
      title: 'Building Resilience in Healthcare Systems',
      date: '2024-10-08',
      description: 'Strategies for building resilience in healthcare systems to withstand crises and disruptions.',
      link: '#',
    },
    {
      id: 15,
      title: 'Blockchain in Healthcare: Secure and Transparent Data Management',
      date: '2024-10-10',
      description: 'Understand how blockchain technology can be used for secure and transparent healthcare data management.',
      link: '#',
    },
    {
      id: 16,
      title: 'The Future of Personalized Medicine',
      date: '2024-10-12',
      description: 'Explore the future of personalized medicine and its implications for patient care.',
      link: '#',
    },
    {
      id: 17,
      title: 'Leveraging Big Data in Healthcare',
      date: '2024-10-15',
      description: 'Learn how to leverage big data in healthcare for improved patient outcomes and operational efficiency.',
      link: '#',
    },
    {
      id: 18,
      title: 'Mobile Health Apps: Enhancing Patient Engagement',
      date: '2024-10-18',
      description: 'Discover how mobile health apps are enhancing patient engagement and care delivery.',
      link: '#',
    },
    {
      id: 19,
      title: 'Improving Healthcare Access with Digital Solutions',
      date: '2024-10-22',
      description: 'Learn about digital solutions that are improving healthcare access in underserved areas.',
      link: '#',
    },
    {
      id: 20,
      title: 'Virtual Reality in Medical Training',
      date: '2024-10-20',
      description: 'Explore how virtual reality is being used for medical training and education.',
      link: '#',
    },
    {
      id: 21,
      title: 'Managing Mental Health in Healthcare Workers',
      date: '2024-07-20',
      description: 'Explore strategies for supporting mental health among healthcare workers.',
      link: '#',
    },
    {
      id: 22,
      title: 'Pandemic Preparedness and Response',
      date: '2024-06-15',
      description: 'Learn about best practices for pandemic preparedness and response in healthcare settings.',
      link: '#',
    },
    {
      id: 23,
      title: 'Advancements in Telehealth',
      date: '2024-05-10',
      description: 'Discover recent advancements in telehealth and their impact on patient care.',
      link: '#',
    },
    {
      id: 24,
      title: 'Effective Communication in Healthcare',
      date: '2024-04-22',
      description: 'Learn how to improve communication among healthcare teams for better patient outcomes.',
      link: '#',
    },
    {
      id: 25,
      title: 'Patient Safety and Quality Improvement',
      date: '2024-03-30',
      description: 'Understand key strategies for improving patient safety and quality in healthcare.',
      link: '#',
    },
    {
      id: 26,
      title: 'Patient Safety and Quality Improvement',
      date: '2024-12-30',
      description: 'Understand key strategies for improving patient safety and quality in healthcare.',
      link: '#',
    },
  ];
